/**
 * rust SDK for OpenFGA
 *
 * API version: 0.1
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://discord.gg/8naAwJfWN6
 * License: [Apache-2.0](https://github.com/openfga/rust-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Difference {
    #[serde(rename = "base")]
    pub base: Box<crate::models::Userset>,
    #[serde(rename = "subtract")]
    pub subtract: Box<crate::models::Userset>,
}

impl Difference {
    pub fn new(base: crate::models::Userset, subtract: crate::models::Userset) -> Difference {
        Difference {
            base: Box::new(base),
            subtract: Box::new(subtract),
        }
    }
}


