/**
 * rust SDK for OpenFGA
 *
 * API version: 0.1
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://discord.gg/8naAwJfWN6
 * License: [Apache-2.0](https://github.com/openfga/rust-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationMetadata {
    #[serde(rename = "directly_related_user_types", skip_serializing_if = "Option::is_none")]
    pub directly_related_user_types: Option<Vec<crate::models::RelationReference>>,
}

impl RelationMetadata {
    pub fn new() -> RelationMetadata {
        RelationMetadata {
            directly_related_user_types: None,
        }
    }
}


