/**
 * rust SDK for OpenFGA
 *
 * API version: 0.1
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://discord.gg/8naAwJfWN6
 * License: [Apache-2.0](https://github.com/openfga/rust-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */

/// RelationReference : RelationReference represents a relation of a particular object type (e.g. 'document#viewer').



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationReference {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "relation", skip_serializing_if = "Option::is_none")]
    pub relation: Option<String>,
    #[serde(rename = "wildcard", skip_serializing_if = "Option::is_none")]
    pub wildcard: Option<serde_json::Value>,
}

impl RelationReference {
    /// RelationReference represents a relation of a particular object type (e.g. 'document#viewer').
    pub fn new(r#type: String) -> RelationReference {
        RelationReference {
            r#type,
            relation: None,
            wildcard: None,
        }
    }
}


