/**
 * rust SDK for OpenFGA
 *
 * API version: 0.1
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://discord.gg/8naAwJfWN6
 * License: [Apache-2.0](https://github.com/openfga/rust-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TupleToUserset {
    #[serde(rename = "tupleset", skip_serializing_if = "Option::is_none")]
    pub tupleset: Option<Box<crate::models::ObjectRelation>>,
    #[serde(rename = "computedUserset", skip_serializing_if = "Option::is_none")]
    pub computed_userset: Option<Box<crate::models::ObjectRelation>>,
}

impl TupleToUserset {
    pub fn new() -> TupleToUserset {
        TupleToUserset {
            tupleset: None,
            computed_userset: None,
        }
    }
}


