/**
 * rust SDK for OpenFGA
 *
 * API version: 0.1
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://discord.gg/8naAwJfWN6
 * License: [Apache-2.0](https://github.com/openfga/rust-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TupleOperation {
    #[serde(rename = "TUPLE_OPERATION_WRITE")]
    Write,
    #[serde(rename = "TUPLE_OPERATION_DELETE")]
    Delete,

}

impl ToString for TupleOperation {
    fn to_string(&self) -> String {
        match self {
            Self::Write => String::from("TUPLE_OPERATION_WRITE"),
            Self::Delete => String::from("TUPLE_OPERATION_DELETE"),
        }
    }
}

impl Default for TupleOperation {
    fn default() -> TupleOperation {
        Self::Write
    }
}




