/**
 * rust SDK for OpenFGA
 *
 * API version: 0.1
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://discord.gg/8naAwJfWN6
 * License: [Apache-2.0](https://github.com/openfga/rust-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UsersetTreePeriodDifference {
    #[serde(rename = "base", skip_serializing_if = "Option::is_none")]
    pub base: Option<Box<crate::models::Node>>,
    #[serde(rename = "subtract", skip_serializing_if = "Option::is_none")]
    pub subtract: Option<Box<crate::models::Node>>,
}

impl UsersetTreePeriodDifference {
    pub fn new() -> UsersetTreePeriodDifference {
        UsersetTreePeriodDifference {
            base: None,
            subtract: None,
        }
    }
}


