/**
 * rust SDK for OpenFGA
 *
 * API version: 0.1
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://discord.gg/8naAwJfWN6
 * License: [Apache-2.0](https://github.com/openfga/rust-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WriteRequest {
    #[serde(rename = "writes", skip_serializing_if = "Option::is_none")]
    pub writes: Option<Box<crate::models::TupleKeys>>,
    #[serde(rename = "deletes", skip_serializing_if = "Option::is_none")]
    pub deletes: Option<Box<crate::models::TupleKeys>>,
    #[serde(rename = "authorization_model_id", skip_serializing_if = "Option::is_none")]
    pub authorization_model_id: Option<String>,
}

impl WriteRequest {
    pub fn new() -> WriteRequest {
        WriteRequest {
            writes: None,
            deletes: None,
            authorization_model_id: None,
        }
    }
}


