/**
 * rust SDK for OpenFGA
 *
 * API version: 0.1
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://discord.gg/8naAwJfWN6
 * License: [Apache-2.0](https://github.com/openfga/rust-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WriteAuthorizationModelRequest {
    #[serde(rename = "type_definitions")]
    pub type_definitions: Vec<crate::models::TypeDefinition>,
    #[serde(rename = "schema_version", skip_serializing_if = "Option::is_none")]
    pub schema_version: Option<String>,
}

impl WriteAuthorizationModelRequest {
    pub fn new(type_definitions: Vec<crate::models::TypeDefinition>) -> WriteAuthorizationModelRequest {
        WriteAuthorizationModelRequest {
            type_definitions,
            schema_version: None,
        }
    }
}


